spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-config
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver     #数据库驱动
    url: jdbc:mysql://localhost:3306/clouddb01?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: zyc30yc2278
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
    initialization-mode: always
mybatis:
  config-location: classpath:mybatis/mybatis.configuration.xml  #myabtis配置文件所在的路径
  type-aliases-package: com.zhang.springcloud.entities      #所有的Entities别名类所在的包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml         #mapper映射文件
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true

info:
  app.name: zhang-microservicecloud
  company.name: www.zhang.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-config
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver     #数据库驱动
    url: jdbc:mysql://localhost:3306/clouddb02?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: zyc30yc2278
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
    initialization-mode: always
mybatis:
  config-location: classpath:mybatis/mybatis.configuration.xml  #myabtis配置文件所在的路径
  type-aliases-package: com.zhang.springcloud.entities      #所有的Entities别名类所在的包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml         #mapper映射文件
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true

info:
  app.name: zhang-microservicecloud
  company.name: www.zhang.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}